name: Passing Vars

on: workflow_dispatch

jobs:
  producer:
    runs-on: ubuntu-latest
    
    outputs: 
      username: ${{steps.generate.outputs.name}}
      lastName: ${{steps.generate.outputs.lastName}}
    
    steps: 
      - name: generate output
        id: generate
        run: |
          echo "name=Mehak" >> $GITHUB_OUTPUT
          echo "lastName=Gaddi" >> $GITHUB_ENV

  consumer:
    runs-on: ubuntu-latest

    needs: producer

    steps: 
      - name: Print output
        run: |
          echo "${{needs.producer.outputs.username}}"
          echo "${{needs.producer.outputs.lastName}}"