name: SecretsAndVariables

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    
    environment: production

    env:
      REPO_SECRET: ${{secrets.DB_Password}}
      REPO_VARIABLE: ${{vars.DB_URL}}

    steps: 
      - name: printing secret
        run: |
          echo "value of the secret is ${REPO_SECRET}"

      - name: printing variable
        run: |
          echo "value of the variable is ${REPO_VARIABLE}"

